services:
  gowatch-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: gowatch-dev
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - PORT=8080
      - GIN_MODE=debug
      - TZ=Europe/Istanbul
      - ADMIN_USERNAME=admin
      # Geliştirme ortamında yerel servislerin izlenebilmesi için
      - ALLOW_PRIVATE_TARGETS=true
