FROM golang:1.25-alpine

RUN apk add --no-cache gcc musl-dev
RUN go install github.com/air-verse/air@latest

WORKDIR /app
COPY go.mod go.sum ./
RUN GOTOOLCHAIN=auto go mod download

# Uygulama kodları docker-compose ile volume olarak bağlanacak, 
# bu yüzden COPY . . yapmıyoruz. Sadece air'i başlatıyoruz.
CMD ["air", "-c", ".air.toml"]
